# These are supported funding model platforms

github: [apetree100122]
patreon: # 
open_collective: # 
ko_fi: # 
tidelift: # 
community_bridge: #
liberapay: # 
issuehunt: #  
otechie: # 
lfx: # [apetree1001@email.phoenix.edu]
